name: dio_logging_interceptor_v2
description: "An Dio interceptor which logs HTTP request and response data"
version: 1.0.3
repository: https://github.com/rizkyghofur/dio_logging_interceptor_v2

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  dio: ^5.5.0+1
