name: dio_logging_interceptor_v2
description: "An Dio interceptor which logs HTTP request and response data"
version: 1.0.1
repository: https://github.com/rizkyghofur/dio_logging_interceptor_v2

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
